# .github/workflows/deploy.yml
name: Deploy to Server

on:
  push:
    branches:
      - main  # mainブランチにpushされたときに動作

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy
        uses: actions/checkout@v2

      - name: SSH into server and deploy
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USERNAME }}
          key: ${{ secrets.DEPLOY_KEY }}
          port: ${{ secrets.SSH_PORT }}
          script: |
            cd ${{ secrets.SERVER_DEPLOY_DIR }}
            git pull origin main