name: Deploy to Onamae Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.DEPLOY_KEY }}

      - name: Install rsync
        run: sudo apt-get update && sudo apt-get install -y rsync

      - name: Sync files via rsync
        run: |
          rsync -avz -e "ssh -p 8022 -o StrictHostKeyChecking=no" ./* r6577176@www325.onamae.ne.jp:/home/egn5n_r6577176/public_html/kazu107.com
